-- CreateTable
CREATE TABLE "verificaciones" (
    "id" TEXT NOT NULL,
    "fecha" TIMESTAMP(3) NOT NULL,
    "carreraProfesional" TEXT NOT NULL,
    "cantidadAulas" INTEGER NOT NULL,
    "nombresAulas" TEXT[],
    "proyectorLimpieza" BOOLEAN NOT NULL DEFAULT false,
    "proyectorEncendido" BOOLEAN NOT NULL DEFAULT false,
    "proyectorCalibracion" BOOLEAN NOT NULL DEFAULT false,
    "proyectorCalibracionImg" TEXT,
    "proyectorHdmi" BOOLEAN NOT NULL DEFAULT false,
    "proyectorHdmiEstado" TEXT,
    "minipcEncendido" BOOLEAN NOT NULL DEFAULT false,
    "minipcSistemaOperativo" BOOLEAN NOT NULL DEFAULT false,
    "minipcIpNombre" TEXT,
    "minipcAntivirus" BOOLEAN NOT NULL DEFAULT false,
    "minipcOffice" BOOLEAN NOT NULL DEFAULT false,
    "minipcTiempoUso" TEXT,
    "minipcPerifericos" BOOLEAN NOT NULL DEFAULT false,
    "minipcPerifericosEstado" TEXT,
    "minipcConectividad" BOOLEAN NOT NULL DEFAULT false,
    "minipcConectividadImg" TEXT,
    "pizarraInstalacion" BOOLEAN NOT NULL DEFAULT false,
    "pizarraCalibracion" BOOLEAN NOT NULL DEFAULT false,
    "pizarraSoftware" BOOLEAN NOT NULL DEFAULT false,
    "pizarraSincronizacion" BOOLEAN NOT NULL DEFAULT false,
    "audioSonido" BOOLEAN NOT NULL DEFAULT false,
    "audioNitidez" BOOLEAN NOT NULL DEFAULT false,
    "internetConectividad" BOOLEAN NOT NULL DEFAULT false,
    "internetConectividadImg" TEXT,
    "internetCobertura" BOOLEAN NOT NULL DEFAULT false,
    "operativas" BOOLEAN NOT NULL DEFAULT true,
    "observaciones" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "verificaciones_pkey" PRIMARY KEY ("id")
);
